[build]
  command = "npm run build"
  functions = ".netlify/functions"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=/opt/buildhome/repo"

[[plugins]]
  package = "@netlify/plugin-nextjs"