import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const allStudentsData = [
  {
    id: 'cmeybuwk70001jwfmnzi1fb6g',
    studentId: 'STU-91BB7E',
    firstName: 'Rolly',
    lastName: 'Paredes',
    middleName: 'O',
    gender: 'Male',
    birthDate: new Date('1994-10-05T00:00:00.000Z'),
    age: 30,
    birthPlace: 'Roxas City',
    contactNumber: '09857917445',
    email: 'rollyparedesva2@gmail.com',
    address: 'Sitio Agbatang',
    region: 'Region VI (Western Visayas)',
    province: 'Capiz',
    cityMunicipality: 'City of Roxas',
    barangay: 'Balijuagan',
    zipCode: '5800',
    guardianFirstName: 'Rolly',
    guardianLastName: 'Paredes',
    guardianMiddleName: 'O',
    guardianContactNumber: '09857917445',
    guardianAddress: 'Sitio Agbatang West, Balijuagan, Roxas City',
    guardianRelationship: 'Parent',
    school: 'Capiz State University Main Campus - Roxas City',
    course: 'Bachelor of Science in Criminology',
    graduationYear: '2025',
    howDidYouKnow: 'Social Media',
    profileImage: '/learning-1.jpg',
    status: 'active',
    createdAt: new Date('2025-08-30T13:58:50.395Z'),
    updatedAt: new Date('2025-08-30T13:59:21.272Z')
  },
  {
    id: 'cmeycy7c6000rjwfmmfmldivk',
    studentId: 'STU-205F30',
    firstName: 'JEZREEL MAE',
    lastName: 'COLAS',
    middleName: 'B',
    gender: 'Female',
    birthDate: new Date('2003-01-05T00:00:00.000Z'),
    age: 22,
    birthPlace: 'MALOCLOC SUR, IVISAN, CAPIZ',
    contactNumber: '09705129454',
    email: 'jezreelmaecolas05@gmail.com',
    address: 'SITIO MAHAYAG BRGY. MALOCLOC SUR, IVISAN, CAPIZ',
    region: 'Region VI (Western Visayas)',
    province: 'Capiz',
    cityMunicipality: 'Ivisan',
    barangay: 'Malocloc Sur',
    zipCode: '5805',
    guardianFirstName: 'JELLYN',
    guardianLastName: 'COLAS',
    guardianMiddleName: 'B',
    guardianContactNumber: '0912462049',
    guardianAddress: 'MALOCLOC SUR, IVISAN, CAPIZ',
    guardianRelationship: 'Sibling',
    school: 'Capiz State University - Dayao Campus (Roxas City)',
    course: 'Bachelor of Science in Criminology',
    graduationYear: '2024-2025',
    howDidYouKnow: 'School',
    profileImage: '/image-2.jpg',
    status: 'active',
    createdAt: new Date('2025-08-30T14:29:23.939Z'),
    updatedAt: new Date('2025-08-30T15:00:27.573Z')
  },
  {
    id: 'cmf0wh51i0000l4gux1w14gs2',
    studentId: 'STU-BB97CE',
    firstName: 'Ashley Ace',
    lastName: 'Clarito',
    middleName: null,
    gender: 'Female',
    birthDate: new Date('2002-11-21T00:00:00.000Z'),
    age: 22,
    birthPlace: 'Roxas City',
    contactNumber: '09102297354',
    email: 'claritoashleyace@gmail.com',
    address: 'Brgy Mongpong',
    region: 'Region VI (Western Visayas)',
    province: 'Capiz',
    cityMunicipality: 'City of Roxas',
    barangay: 'Mongpong',
    zipCode: '5800',
    guardianFirstName: 'Arlene',
    guardianLastName: 'Adriatico',
    guardianMiddleName: null,
    guardianContactNumber: '09636638038',
    guardianAddress: 'Brgy mongpong Roxas city Capiz',
    guardianRelationship: 'Parent',
    school: 'Capiz State University Dayao Satellite College',
    course: 'Bachelor of Science in Criminology',
    graduationYear: '2025',
    howDidYouKnow: 'School',
    profileImage: '/image-3.jpg',
    status: 'active',
    createdAt: new Date('2025-09-01T09:11:32.546Z'),
    updatedAt: new Date('2025-09-01T09:52:01.414Z')
  },
  {
    id: 'cmeyygogt0000g4eamzrduvb7',
    studentId: 'STU-1D9F7B',
    firstName: 'Reynaldo',
    lastName: 'Baniel',
    middleName: null,
    gender: 'Male',
    birthDate: new Date('1996-09-06T00:00:00.000Z'),
    age: 28,
    birthPlace: 'Memorial',
    contactNumber: '09927428987',
    email: 'reynaldobaniel1@gmail.com',
    address: 'Tambak',
    region: 'Region VI (Western Visayas)',
    province: 'Capiz',
    cityMunicipality: 'Pontevedra',
    barangay: 'Ilawod',
    zipCode: '5802',
    guardianFirstName: 'Lilibeth',
    guardianLastName: 'Baniel',
    guardianMiddleName: 'D',
    guardianContactNumber: '09455589812',
    guardianAddress: 'Arcabalo bolo',
    guardianRelationship: 'Parent',
    school: 'Capiz State University - Dayao Campus (Roxas City)',
    course: 'Bachelor of Science in Criminology',
    graduationYear: '2025',
    howDidYouKnow: 'Friend/Relative',
    referredBy: 'Justin tanalgo',
    profileImage: '/image-2.jpg',
    status: 'active',
    createdAt: new Date('2025-08-31T00:31:37.949Z'),
    updatedAt: new Date('2025-09-01T06:46:48.058Z')
  },
  {
    id: 'cmeycjjpr0006jwfmpdjvxzpu',
    studentId: 'STU-E919A5',
    firstName: 'Kenneth',
    lastName: 'Vicente',
    middleName: null,
    gender: 'Male',
    birthDate: new Date('2002-08-25T00:00:00.000Z'),
    age: 23,
    birthPlace: 'Sigma,Capiz',
    contactNumber: '09638001133',
    email: 'vicentekenneth2@gmail.com',
    address: 'Purok 1',
    region: 'Region VI (Western Visayas)',
    province: 'Capiz',
    cityMunicipality: 'Sigma',
    barangay: 'Acbo',
    zipCode: '5816',
    guardianFirstName: 'Gemma',
    guardianLastName: 'Vicente',
    guardianMiddleName: null,
    guardianContactNumber: '(0948) 320 7067',
    guardianAddress: 'Brgy.Acbo, Sigma, Capiz',
    guardianRelationship: 'Parent',
    school: 'Capiz State University - Dayao Campus (Roxas City)',
    course: 'Bachelor of Science in Criminology',
    graduationYear: '2025',
    howDidYouKnow: 'Friend/Relative',
    referredBy: 'Ashley Ace Clarito',
    profileImage: '/learning-1.jpg',
    status: 'active',
    createdAt: new Date('2025-08-30T14:18:00.108Z'),
    updatedAt: new Date('2025-08-30T14:19:27.193Z')
  },
  {
    id: 'cmeyct8el000fjwfmkuybldqw',
    studentId: 'STU-09ED32',
    firstName: 'Ray Andre',
    lastName: 'babila',
    middleName: 'R',
    gender: 'Male',
    birthDate: new Date('2002-07-22T00:00:00.000Z'),
    age: 23,
    birthPlace: 'Pontevedra capiz',
    contactNumber: '09639863973',
    email: 'rayandrebabela22@gamail.com',
    address: 'Isagani street. Pontevedra capiz',
    region: 'Region VI (Western Visayas)',
    province: 'Capiz',
    cityMunicipality: 'Pontevedra',
    barangay: 'Ilawod',
    zipCode: '5802',
    guardianFirstName: 'Arlaine',
    guardianLastName: 'babela',
    guardianMiddleName: 'R',
    guardianContactNumber: '09489832611',
    guardianAddress: 'Ilawod pontevedra capiz',
    guardianRelationship: 'Parent',
    school: 'Capiz State University - Dayao Campus (Roxas City)',
    course: 'Bachelor of Science in Criminology',
    graduationYear: '2024-2025',
    howDidYouKnow: 'Friend/Relative',
    referredBy: 'Senatin razel',
    profileImage: '/background-image.jpg',
    status: 'active',
    createdAt: new Date('2025-08-30T14:25:32.044Z'),
    updatedAt: new Date('2025-08-30T14:58:05.766Z')
  },
  {
    id: 'cmeyctq6e000ijwfmf9vbbck5',
    studentId: 'STU-2DCCAC',
    firstName: 'Jamella',
    lastName: 'Aminoso',
    middleName: 'B',
    gender: 'Female',
    birthDate: new Date('2002-11-17T00:00:00.000Z'),
    age: 22,
    birthPlace: 'Roxas Memorial Provincial Hospital',
    contactNumber: '09203975677',
    email: 'jamellaamnso@mail.com',
    address: 'Bargy Cogon Proper Roxas City',
    region: 'Region VI (Western Visayas)',
    province: 'Capiz',
    cityMunicipality: 'City of Roxas',
    barangay: 'Cogon',
    zipCode: '5800',
    guardianFirstName: 'Juan',
    guardianLastName: 'Aminoso',
    guardianMiddleName: 'A',
    guardianContactNumber: '09633907393',
    guardianAddress: 'Brgy Cogon Roxas City',
    guardianRelationship: 'Parent',
    school: 'Capiz State University - Dayao Campus (Roxas City)',
    course: 'Bachelor of Science in Criminology',
    graduationYear: '2025',
    howDidYouKnow: 'Friend/Relative',
    referredBy: 'N/A',
    profileImage: '/learning-1.jpg',
    status: 'active',
    createdAt: new Date('2025-08-30T14:25:55.077Z'),
    updatedAt: new Date('2025-08-30T15:00:15.997Z')
  },
  {
    id: 'cmeydj5w60010jwfm373ogcq5',
    studentId: 'STU-C5314D',
    firstName: 'KEVIN',
    lastName: 'OCHAVEZ',
    middleName: 'G',
    gender: 'Male',
    birthDate: new Date('1999-11-12T00:00:00.000Z'),
    age: 25,
    birthPlace: 'Majanlud Sapian Capiz',
    contactNumber: '09814124798',
    email: 'ochavezkevin@gmail.com',
    address: 'Mission hills',
    region: 'Region VI (Western Visayas)',
    province: 'Capiz',
    cityMunicipality: 'City of Roxas',
    barangay: 'Milibili',
    zipCode: '5800',
    guardianFirstName: 'Jorge',
    guardianLastName: 'Marcellana',
    guardianMiddleName: 'O',
    guardianContactNumber: '0909 086 0263',
    guardianAddress: 'Barangay milibili Roxas city Capiz',
    guardianRelationship: 'Other',
    school: 'Capiz State University - Dayao Campus (Roxas City)',
    course: 'Bachelor of Science in Criminology',
    graduationYear: '2024',
    howDidYouKnow: 'Friend/Relative',
    referredBy: 'Blessie',
    profileImage: '/image-1.jpg',
    status: 'active',
    createdAt: new Date('2025-08-30T14:45:41.847Z'),
    updatedAt: new Date('2025-08-30T15:00:57.905Z')
  },
  {
    id: 'cmeydgwae000xjwfmrwonvbby',
    studentId: 'STU-E1352A',
    firstName: 'KRISTINE ROSE',
    lastName: 'SANGRINES',
    middleName: 'B',
    gender: 'Female',
    birthDate: new Date('2001-09-22T00:00:00.000Z'),
    age: 23,
    birthPlace: 'BATAD TANAO, ILOILO',
    contactNumber: '09386415041',
    email: 'sangrineskristine@gmail.com',
    address: 'St.GUINTUNORAN',
    region: 'Region VI (Western Visayas)',
    province: 'Capiz',
    cityMunicipality: 'Pilar',
    barangay: 'Natividad',
    zipCode: '5804',
    guardianFirstName: 'GELIE',
    guardianLastName: 'TIBUYIN',
    guardianMiddleName: 'B',
    guardianContactNumber: '09502264074',
    guardianAddress: 'TIZA ROXAS CITY, CAPIZ',
    guardianRelationship: 'Relative',
    school: 'Capiz State University - Dayao Campus (Roxas City)',
    course: 'Bachelor of Science in Criminology',
    graduationYear: '2024-2025',
    howDidYouKnow: 'School',
    profileImage: '/image-2.jpg',
    status: 'active',
    createdAt: new Date('2025-08-30T14:43:56.080Z'),
    updatedAt: new Date('2025-08-30T15:00:47.873Z')
  },
  {
    id: 'cmeyd2ywc000ujwfmujef4p16',
    studentId: 'STU-9E70C0',
    firstName: 'Jairelle',
    lastName: 'De Pedro',
    middleName: 'S',
    gender: 'Male',
    birthDate: new Date('2001-08-01T00:00:00.000Z'),
    age: 24,
    birthPlace: 'Tiza Roxas city, Capiz',
    contactNumber: '09511538831',
    email: 'jairelle.depedro@hercorcollege.edu.ph',
    address: 'Punta tabuc Roxas city, Capiz',
    region: 'Region VI (Western Visayas)',
    province: 'Capiz',
    cityMunicipality: 'City of Roxas',
    barangay: 'Punta Tabuc',
    zipCode: '5800',
    guardianFirstName: 'Elmer',
    guardianLastName: 'De Pedro',
    guardianMiddleName: 'C',
    guardianContactNumber: '09939787517',
    guardianAddress: 'Punta Tabuc Roxas City, Capiz',
    guardianRelationship: 'Parent',
    school: 'Hercor College (Roxas City)',
    course: 'Bachelor of Science in Criminology',
    graduationYear: '2024-2025',
    howDidYouKnow: 'Friend/Relative',
    profileImage: '/image-3.jpg',
    status: 'active',
    createdAt: new Date('2025-08-30T14:33:06.348Z'),
    updatedAt: new Date('2025-08-30T15:00:38.428Z')
  },
  {
    id: 'cmeye1niv0013jwfmiuf32e9p',
    studentId: 'STU-7A1669',
    firstName: 'Leslie',
    lastName: 'Vacaro',
    middleName: 'M',
    gender: 'Female',
    birthDate: new Date('2003-09-18T00:00:00.000Z'),
    age: 21,
    birthPlace: 'Cagay Roxas City',
    contactNumber: '09930924234',
    email: 'leslievacaro24@gmail.com',
    address: 'Cagay Roxas City, Capiz',
    region: 'Region VI (Western Visayas)',
    province: 'Capiz',
    cityMunicipality: 'City of Roxas',
    barangay: 'Cagay',
    zipCode: '5800',
    guardianFirstName: 'Frederick',
    guardianLastName: 'Vacaro',
    guardianMiddleName: 'U',
    guardianContactNumber: '09096298819',
    guardianAddress: 'Cagay Roxas City, Capiz',
    guardianRelationship: 'Parent',
    school: 'Capiz State University - Dayao Campus (Roxas City)',
    course: 'Bachelor of Science in Criminology',
    graduationYear: '2024-2025',
    howDidYouKnow: 'School',
    profileImage: '/background-image.jpg',
    status: 'active',
    createdAt: new Date('2025-08-30T15:00:04.567Z'),
    updatedAt: new Date('2025-08-30T15:10:58.220Z')
  },
  {
    id: 'cmeyhu1w40000g2fk6hhndl3p',
    studentId: 'STU-456ED9',
    firstName: 'Cyren',
    lastName: 'Duran',
    middleName: 'E',
    gender: 'Female',
    birthDate: new Date('2003-01-06T00:00:00.000Z'),
    age: 22,
    birthPlace: 'January 06, 2003',
    contactNumber: '09317745471',
    email: 'durancyrene@gmail.com',
    address: 'Sitio agsagoksok brgy Mainit Cuartero Capiz',
    region: 'Region VI (Western Visayas)',
    province: 'Capiz',
    cityMunicipality: 'Cuartero',
    barangay: 'Mainit',
    zipCode: '5811',
    guardianFirstName: 'Jimmy',
    guardianLastName: 'Duran',
    guardianMiddleName: 'A',
    guardianContactNumber: '09914413440',
    guardianAddress: 'Sitio agsagoksok brgy Mainit Cuartero Capiz',
    guardianRelationship: 'Parent',
    school: 'Capiz State University - Dayao Campus (Roxas City)',
    course: 'Bachelor of Science in Criminology',
    graduationYear: '2025',
    howDidYouKnow: 'Friend/Relative',
    profileImage: '/learning-1.jpg',
    status: 'active',
    createdAt: new Date('2025-08-30T16:46:08.330Z'),
    updatedAt: new Date('2025-08-30T23:22:11.423Z')
  },
  {
    id: 'cmeyo61tg0000fqjq4b0jeol2',
    studentId: 'STU-F950DF',
    firstName: 'Paulline',
    lastName: 'Libardo',
    middleName: 'B',
    gender: 'Female',
    birthDate: new Date('2003-09-03T00:00:00.000Z'),
    age: 21,
    birthPlace: 'Quezon Memorial Center',
    contactNumber: '09285806601',
    email: 'libardopaulline03@gmail.com',
    address: 'Barangay Atiplo Mambusao Capiz',
    region: 'Region VI (Western Visayas)',
    province: 'Capiz',
    cityMunicipality: 'Mambusao',
    barangay: 'Atiplo',
    zipCode: '5806',
    guardianFirstName: 'Lito',
    guardianLastName: 'Libardo',
    guardianMiddleName: 'L',
    guardianContactNumber: '09107595718',
    guardianAddress: 'Barangay Atiplo Mambusao capiz',
    guardianRelationship: 'Parent',
    school: 'Capiz State University - Dayao Campus (Roxas City)',
    course: 'Bachelor of Science in Criminology',
    graduationYear: '2024-2025',
    howDidYouKnow: 'Friend/Relative',
    profileImage: '/image-1.jpg',
    status: 'active',
    createdAt: new Date('2025-08-30T19:43:25.873Z'),
    updatedAt: new Date('2025-08-30T23:22:21.612Z')
  },
  {
    id: 'cmeycove70009jwfmk90uz49w',
    studentId: 'STU-BADD09',
    firstName: 'BLESSIE MAY',
    lastName: 'REYES',
    middleName: 'I',
    gender: 'Female',
    birthDate: new Date('2002-08-13T00:00:00.000Z'),
    age: 23,
    birthPlace: 'ROXAS CITY',
    contactNumber: '09102408473',
    email: 'reyesblessiemay34@gmail.com',
    address: 'Sitio Escuala, Brgy. Balijuagan, Roxas City',
    region: 'Region VI (Western Visayas)',
    province: 'Capiz',
    cityMunicipality: 'City of Roxas',
    barangay: 'Balijuagan',
    zipCode: '5800',
    guardianFirstName: 'PECHIE',
    guardianLastName: 'REYES',
    guardianMiddleName: 'I',
    guardianContactNumber: '09511305769',
    guardianAddress: 'Sitio Escuala, Brgy. Balijuagan, Roxas City',
    guardianRelationship: 'Parent',
    school: 'Capiz State University - Dayao Campus (Roxas City)',
    course: 'Bachelor of Science in Criminology',
    graduationYear: '2025',
    howDidYouKnow: 'School',
    profileImage: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEABISEhITEhQWFhQcHhseHCkmIiImKT4sMCwwLD5eO0U7O0U7XlNlUk1SZVOWdmhodpatkYqRrdK8vNL/+/////8BEhISEhMSFBYWFBweGx4cKSYiIiYpPiwwLDAsPl47RTs7RTteU2VSTVJlU5Z2aGh2lq2RipGt0ry80v/7///////CABEIBCgENwMBIgACEQEDEQH/xAAvAAEBAQEBAQAAAAAAAAAAAAAAAQIDBAUBAQEBAQEAAAAAAAAAAAAAAAABAgME/9oADAMBAAIQAxAAAALyCwAAAAAKUAQAFAioiiKIoigKBBSKIolAAAAQAoAFlAooAAAAAASiAAAAACEogAAAAACCoKAAACLAAAAACKIAPPxDv3',
    status: 'active',
    createdAt: new Date('2025-08-30T14:21:23.939Z'),
    updatedAt: new Date('2025-08-30T15:00:27.573Z')
  }
]

async function main() {
  console.log('Importing all 28 students...')
  
  for (const student of allStudentsData) {
    await prisma.student.upsert({
      where: { id: student.id },
      update: student,
      create: student,
    })
  }
  
  console.log(`✅ Successfully imported ${allStudentsData.length} students!`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })