name: Sync Philippine Institutions

on:
  schedule:
    # Run daily at 2 AM UTC (10 AM PHT)
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate Prisma client
      run: npx prisma generate
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        
    - name: Run institutions sync
      run: npx tsx scripts/sync-institutions.ts
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        
    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Institutions Sync Failed',
            body: `The scheduled institutions sync failed. Please check the workflow logs.`
          })